version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-bom"
        versions: [ ">=12.1.0" ]
      - dependency-name: "org.eclipse.jetty.ee10:*"
        versions: [ ">=12.1.0" ]
      - dependency-name: "org.eclipse.jetty:jetty-reactive-httpclient"
        versions: [ ">=4.1.0" ]
