name: Release Drafter
on:
  workflow_call:
  push:
    branches:
      - main

permissions:
  security-events: read
  contents: write
  actions: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
